### ISSUE TITLE
Implement title page

### ISSUE THREAD

**Issue by catouberos** [tanamoe/kikuri#111]
- [x] Basic information (incl. title, description, cover, releases and covers) - #102 
- [x] Gallery view for book covers (incl. light-box) - #144 
- [x] Details information view on side (incl. artist/author, translator, etc.) - #161
- [x] Details information on each publication (incl. ISBN, etc.) - needed discussions
