### ISSUE TITLE
Improve SEO

### ISSUE THREAD

**Issue by catouberos** [tanamoe/kikuri#112]
- [x] Basic title and favicon - #109 
- [ ] Advanced SEO tags - #161 
- [ ] OG image endpoint - #161
